server:
  port: 10010
spring:
  application:
    name: leyou-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜素微服务的映射路径
    user-service: /user/** #用户微服务
    auth-service: /auth/** # 授权中心微服务
  retryable: true
ribbon:
  ConnectTimeout: 60000 # 连接超时时间(ms)
  ReadTimeout: 60000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
