server:
  port: 8083
spring:
  application:
    name: search-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
  data:
    elasticsearch:
      cluster-nodes: 192.168.15.128:9300
  jackson:
    default-property-inclusion: non_null #将为null的json数据过滤掉
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}