server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  #关闭缓存便于开发
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳