server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.15.128
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: mysql
#  data:
#    mongodb:
#      host: 192.168.15.128
#      database: cart
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
leyou:
  jwt:
    secret: leyou # 登录校验的密钥
    pubKeyPath: D:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN